site_name: Siddhi-Execution-Time
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Execution Time: index.md
- API Docs:
  - 4.0.5: api/4.0.5.md
  - latest: api/latest.md
- License: license.md
theme: material
